onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /test_bench_16b/inst_cos_sin/i_clk
add wave -noupdate /test_bench_16b/i_channel
add wave -noupdate /test_bench_16b/o_channel
add wave -noupdate /test_bench_16b/inst_cos_sin/s_channel
add wave -noupdate -divider {New Divider}
add wave -noupdate /test_bench_16b/inst_cos_sin/i_X
add wave -noupdate /test_bench_16b/inst_cos_sin/i_Y
add wave -noupdate -radix hexadecimal /test_bench_16b/inst_cos_sin/i_Z
add wave -noupdate -divider {New Divider}
add wave -noupdate -childformat {{/test_bench_16b/inst_cos_sin/s_X(16) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(15) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(14) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(13) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(12) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(11) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(10) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(9) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(8) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(7) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(6) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(5) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(4) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(3) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(2) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(1) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_X(0) -radix hexadecimal}} -expand -subitemconfig {/test_bench_16b/inst_cos_sin/s_X(16) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(15) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(14) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(13) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(12) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(11) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(10) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(9) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(8) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(7) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(6) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(5) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(4) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(3) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(2) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(1) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_X(0) {-height 15 -radix hexadecimal}} /test_bench_16b/inst_cos_sin/s_X
add wave -noupdate -childformat {{/test_bench_16b/inst_cos_sin/s_Y(16) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(15) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(14) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(13) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(12) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(11) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(10) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(9) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(8) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(7) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(6) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(5) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(4) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(3) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(2) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(1) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Y(0) -radix hexadecimal}} -subitemconfig {/test_bench_16b/inst_cos_sin/s_Y(16) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(15) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(14) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(13) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(12) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(11) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(10) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(9) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(8) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(7) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(6) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(5) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(4) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(3) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(2) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(1) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Y(0) {-height 15 -radix hexadecimal}} /test_bench_16b/inst_cos_sin/s_Y
add wave -noupdate -childformat {{/test_bench_16b/inst_cos_sin/s_Z(16) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(15) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(14) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(13) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(12) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(11) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(10) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(9) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(8) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(7) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(6) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(5) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(4) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(3) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(2) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(1) -radix hexadecimal} {/test_bench_16b/inst_cos_sin/s_Z(0) -radix hexadecimal}} -subitemconfig {/test_bench_16b/inst_cos_sin/s_Z(16) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(15) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(14) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(13) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(12) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(11) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(10) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(9) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(8) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(7) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(6) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(5) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(4) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(3) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(2) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(1) {-height 15 -radix hexadecimal} /test_bench_16b/inst_cos_sin/s_Z(0) {-height 15 -radix hexadecimal}} /test_bench_16b/inst_cos_sin/s_Z
add wave -noupdate -divider {New Divider}
add wave -noupdate -radix hexadecimal /test_bench_16b/inst_cos_sin/o_X
add wave -noupdate -radix hexadecimal /test_bench_16b/inst_cos_sin/o_Y
add wave -noupdate /test_bench_16b/inst_cos_sin/o_Z
add wave -noupdate /test_bench_16b/i_areset_n
add wave -noupdate -expand /test_bench_16b/inst_cos_sin/s_post
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {9559443 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 107
configure wave -valuecolwidth 162
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {4966500 ps}
